// 모든 화면 문구는 이 파일에서만 관리하세요. 컴포넌트에 문구를 직접 쓰지 마세요.
// 화면별 문구 목록은 docs/copy-list.md에서 함께 관리합니다.

// 표시 라벨은 "소모임"이에요. 내부 코드/테이블/라우트 명칭(bungae)은 그대로 유지해요(docs/decisions.md 참고).
export const TAB_LABELS = {
  feed: '수다방',
  bungae: '소모임',
  me: '내정보',
} as const

// 컨셉: 퇴근길이 아니라 "새벽에 일하는 사람들이 쓰는 SNS"(2026-09-22 사용자 정정)
export const CONCEPT_COPY = {
  tagline: '새벽에도 우리가 있어요',
  bungaeIntro: '새벽에 일하는 사람들, 여기 모여요',
} as const

export const REGION_NOTICE = '전국 어디서나 소모임을 열 수 있어요. 내 활동지역과 가까운 소모임부터 보여드려요.'

export const GUEST_COPY = {
  browseNotice: '둘러보는 중이에요. 글쓰기·좋아요·소모임 참여는 로그인 후 이용할 수 있어요.',
  ctaLogin: '로그인하고 참여하기',
  meLoggedOut: '로그인하고 내 정보를 확인해보세요',
} as const

export const AUTH_COPY = {
  loginTitle: '다시 만나서 반가워요',
  signupTitle: '새벽사람들에 오신 걸 환영해요',
  emailLabel: '이메일',
  passwordLabel: '비밀번호',
  loginSubmit: '로그인',
  signupSubmit: '가입하기',
  switchToSignup: '아직 계정이 없으신가요? 가입하기',
  switchToLogin: '이미 계정이 있으신가요? 로그인',
  signupSuccess: '가입 확인 메일을 보냈어요. 메일함을 확인해 주세요.',
  signupHint: '가입 다음 화면에서 프로필을 설정해요.',
  // 로그인 화면 아래 가입 유도 카드
  signupPromptTitle: '처음 오셨나요?',
  signupPromptDesc: '이메일만 있으면 1분이면 가입해요.',
  signupPromptButton: '가입하기',
  keepLoggedIn: '한 번 로그인하면 로그아웃하기 전까지 로그인 상태가 유지돼요.',
  forgot: '비밀번호를 잊으셨나요?',
  tossLoginTitle: '토스 계정으로 시작해요',
  tossLoginButton: '토스로 로그인',
  tossLoginError: '토스 로그인에 실패했어요. 잠시 후 다시 시도해 주세요.',
  tossLoginNotice: '토스 계정으로 간편하게 시작해요. 실명과 전화번호는 저장하지 않고, 닉네임으로 활동해요.',
} as const

// 앱인토스 첫 로그인 전에 먼저 보여주는 서비스 소개(인트로) 화면. 검수: 설명 없이 바로 토스 로그인을 유도하면 반려돼요.
export const INTRO_COPY = {
  title: '새벽에 일하는 사람들의 SNS',
  desc: '저녁에 출근하고 새벽에 퇴근하는 우리, 낮에만 모임이 있어서 아쉬웠죠? 여기서는 새벽에 일하는 사람들끼리 이야기하고 모여요.',
  features: [
    { icon: 'chat-icon', title: '수다방', desc: '새벽에 깨어 있는 사람들과 글·사진으로 이야기해요.' },
    { icon: 'group-icon', title: '소모임', desc: '퇴근 후 가볍게 모이는 오프라인 소모임에 참여하거나 직접 열어요.' },
    { icon: 'moon-icon', title: '닉네임으로 익명 활동', desc: '실명 없이 새벽 닉네임으로 편하게 활동해요.' },
  ],
  start: '시작하기',
  browse: '먼저 둘러볼게요',
} as const

// 아이디(이메일) 확인·새 비밀번호 발송
export const RESET_COPY = {
  title: '아이디·비밀번호 찾기',
  idInfo: '아이디는 가입할 때 쓴 이메일 주소예요.',
  desc: '가입한 이메일을 입력하면 새 비밀번호를 메일로 보내드려요.',
  submit: '새 비밀번호 받기',
  sending: '보내는 중이에요…',
  done: '가입된 이메일이라면 새 비밀번호를 보냈어요. 메일함(스팸함 포함)을 확인해 주세요.',
  afterLogin: '새 비밀번호로 로그인한 뒤 꼭 [내정보 → 설정 → 비밀번호 변경]에서 비밀번호를 바꿔주세요.',
  tooMany: '요청이 너무 잦아요. 10분 뒤에 다시 시도해 주세요.',
  error: '메일을 보내지 못했어요. 잠시 후 다시 시도해 주세요.',
  close: '로그인하러 가기',
} as const

export const PASSWORD_COPY = {
  title: '비밀번호 변경',
  current: '지금 비밀번호',
  next: '새 비밀번호 (6자 이상)',
  confirm: '새 비밀번호 확인',
  submit: '변경하기',
  mismatch: '새 비밀번호가 서로 달라요.',
  same: '지금 비밀번호와 다른 비밀번호를 입력해 주세요.',
  wrongCurrent: '지금 비밀번호가 맞지 않아요.',
  done: '비밀번호를 바꿨어요.',
  error: '비밀번호를 바꾸지 못했어요. 잠시 후 다시 시도해 주세요.',
  hint: '메일로 받은 임시 비밀번호로 로그인했다면 여기서 새 비밀번호로 바꿔주세요.',
} as const

export const AUTH_ERROR_COPY = {
  emailRateLimit: '지금은 가입 메일을 보낼 수 없어요. 잠시 후 다시 시도해 주세요.',
  requestRateLimit: '요청이 너무 많아요. 잠시 후 다시 시도해 주세요.',
  alreadyRegistered: '이미 가입된 이메일이에요. 로그인해 주세요.',
  invalidCredentials: '이메일 또는 비밀번호가 맞지 않아요.',
  emailNotConfirmed: '메일함에서 가입 확인을 먼저 완료해 주세요.',
  weakPassword: '비밀번호가 너무 쉬워요. 더 길고 복잡하게 만들어 주세요.',
  invalidEmail: '이메일 주소를 다시 확인해 주세요.',
  unknown: '문제가 발생했어요. 잠시 후 다시 시도해 주세요.',
} as const

export const ONBOARDING_COPY = {
  title: '반가워요! 몇 가지만 알려주세요',
  photoLabel: '프로필 사진 (선택)',
  photoHint: '올리지 않으면 기본 이미지로 보여요. 나중에 언제든 바꿀 수 있어요.',
  photoPick: '사진 선택',
  photoReset: '기본 이미지로',
  nicknameLabel: '닉네임',
  reroll: '다시 뽑기',
  bioLabel: '한줄소개 (선택)',
  bioPlaceholder: '예: 새벽 4시에 퇴근하는 간호사예요',
  genderLabel: '성별',
  birthYearLabel: '출생연도',
  under19Notice: '만 19세 이상만 가입할 수 있어요.',
  sidoLabel: '시/도',
  sigunguLabel: '시/군/구',
  locationLabelLabel: '이 지역 이름 (예: 집, 회사)',
  workTypeLabel: '근무 유형 (선택)',
  offTimeBandLabel: '퇴근 시간대 (선택)',
  agreeAll: '모두 동의해요',
  agreeTerms: '[필수] 서비스 이용약관에 동의해요',
  agreePrivacy: '[필수] 개인정보 처리방침에 동의해요',
  agree19: '[필수] 만 19세 이상이에요',
  viewTerms: '서비스 이용약관 보기',
  viewPrivacy: '개인정보 처리방침 보기',
  submit: '시작하기',
  privacyNote: '성별·출생연도는 다른 사람에게 공개되지 않아요. 소모임 참석 현황에서만 연령대로 표시돼요.',
} as const

// 내 활동지역 설정(당근마켓 "동네 설정"과 비슷한 개념, 2026-09-22 "동네"→"활동지역" 표현 변경). 최대 3개까지 저장, 이름 지정 가능(집/회사 등).
export const LOCATION_COPY = {
  sheetTitle: '내 활동지역 설정',
  current: '현재 활동지역',
  savedTitle: '저장한 활동지역',
  switchTo: '이 활동지역으로 보기',
  add: '활동지역 추가',
  addTitle: '활동지역 추가하기',
  labelPlaceholder: '이름 (예: 집, 회사)',
  sidoLabel: '시/도',
  sigunguLabel: '시/군/구',
  save: '저장',
  cancel: '취소',
  full: (max: number) => `활동지역은 최대 ${max}개까지 저장할 수 있어요.`,
  delete: '삭제',
  empty: '아직 저장한 활동지역이 없어요.',
  unset: '지역 미설정',
} as const

export const FEED_COPY = {
  headerTagline: '새벽에 일하는 우리끼리의 공간',
  empty: '아직 글이 없어요. 첫 글을 남겨볼까요?',
  composeTitle: '새 글',
  composeCancel: '취소',
  composeSubmit: '게시',
  composePlaceholder: '새벽에 우리끼리 공유해요',
  composeAddMedia: '사진 추가',
  composeAddFile: '파일 추가',
  contentGuide: '욕설·비방, 성적인 내용, 범죄와 관련된 글은 삭제되거나 이용이 제한될 수 있어요.',
  composeLimit: (max: number) => `첨부는 최대 ${max}개까지 올릴 수 있어요.`,
  composeUploading: '올리는 중이에요…',
  threadTitle: '스레드',
  notFound: '글을 찾을 수 없어요.',
  submitError: '글을 올리지 못했어요. 잠시 후 다시 시도해 주세요.',
  doubleTapHint: '두 번 톡 치면 좋아요',
  deleteConfirm: '이 글을 삭제할까요?',
  deleted: '글을 삭제했어요.',
  deleteError: '글을 삭제하지 못했어요.',
  editError: '글을 수정하지 못했어요.',
  shareCopied: '링크를 복사했어요.',
  like: (n: number) => `좋아요 ${n}`,
  replies: (n: number) => `댓글 ${n}`,
  share: '공유',
  dm: '메시지',
} as const

export const MEDIA_COPY = {
  openImage: '사진 크게 보기',
  remove: '첨부 삭제',
  file: '첨부 파일',
  readMore: '더 보기',
  readLess: '접기',
} as const

export const COMMENT_COPY = {
  title: '답글',
  placeholder: '답글을 남겨보세요',
  placeholderFor: (nickname: string) => `${nickname}님에게 답글 남기기`,
  submit: '등록',
  empty: '아직 답글이 없어요. 첫 답글을 남겨보세요.',
  reply: '답글 달기',
  replyingTo: (nickname: string) => `${nickname}님에게 답글 남기는 중`,
  cancelReply: '취소',
  attachImage: '사진 첨부',
  edited: '수정됨',
  save: '저장',
  cancel: '취소',
  deleteConfirm: '이 답글을 삭제할까요?',
  submitError: '답글을 올리지 못했어요. 잠시 후 다시 시도해 주세요.',
  editError: '답글을 수정하지 못했어요.',
  deleteError: '답글을 삭제하지 못했어요.',
} as const

export const MENU_COPY = {
  more: '더보기',
  edit: '수정하기',
  delete: '삭제하기',
  report: '신고하기',
  block: '차단하기',
  unblock: '차단 해제',
  cancel: '닫기',
  deleteConfirm: '삭제할까요?',
  deleteDesc: '삭제하면 되돌릴 수 없어요.',
  reportTitle: '신고 사유를 골라주세요',
  reportReasons: [
    '욕설·비하·혐오 표현',
    '음란·선정적인 내용',
    '스팸·광고·홍보',
    '사기·금전 요구',
    '개인정보 노출',
    '불법 행위·위험한 모임',
    '기타 부적절한 내용',
  ],
  reportCustom: '직접 입력',
  reportCustomTitle: '신고 사유를 적어주세요',
  reportCustomPlaceholder: '어떤 점이 불편했는지 알려주세요 (500자 이내)',
  reportSubmit: '신고하기',
  reportDone: '신고가 접수됐어요. 확인 후 조치할게요.',
  reportFailed: '신고를 접수하지 못했어요. 잠시 후 다시 시도해 주세요.',
  blockTitle: (nickname: string) => `${nickname}님을 차단할까요?`,
  blockDesc: '서로의 글·답글이 보이지 않고, 팔로우가 끊기며, 메시지를 주고받을 수 없어요.',
  blockDone: '차단했어요.',
  blockFailed: '차단하지 못했어요.',
  unblockDone: '차단을 해제했어요.',
  blockedByOther: '상대방이 차단했어요',
} as const

export const BUNGAE_COPY = {
  listTitle: '소모임',
  empty: '아직 열린 소모임이 없어요. 첫 소모임을 만들어볼까요?',
  upcomingTitle: '다가오는 소모임',
  upcomingCreate: '만들기',
  allTitle: '모든 소모임',
  titleLabel: '제목',
  titlePlaceholder: '예: 새벽 퇴근 후 같이 운동해요',
  bodyLabel: '소개',
  bodyPlaceholder:
    '예: 새벽에 퇴근하고 혼자 심심한데, 같이 모여서 운동도 하고 취미도 나누고 밥도 먹어요.',
  contentGuide: '운동·취미·식사·영화 같은 건전한 활동으로 소개해 주세요. 이성 만남·소개팅 목적의 모임은 제한될 수 있어요.',
  startsAtLabel: '모이는 시각',
  startsAtHint: '기본은 새벽 6시(오전 6시)예요. 지금부터 1시간 이후로 정할 수 있어요.',
  sidoLabel: '시/도',
  sigunguLabel: '시/군/구',
  eupmyeondongLabel: '동/읍/면',
  placeHintLabel: '만나는 장소 (선택)',
  capacityLabel: '정원 (리더 포함 2~10명)',
  safetyNotice: '공개된 장소에서 만나요. 낯선 사람에게 개인정보나 금전을 보내지 마세요.',
  moderationNotice: '욕설·비방, 성적인 내용, 범죄와 관련된 내용은 삭제되거나 이용이 제한될 수 있어요.',
  submit: '만들기',
  remainingSlots: (n: number) => (n > 0 ? `${n}자리 남았어요` : '정원이 가득 찼어요'),
  hideFullToggle: '마감된 모임 제외',
  regionBadgeGuest: '활동지역 설정',
  joinButton: '참석 신청',
  leaveButton: '참석 취소',
  hostBadge: '리더',
  participantsRestricted: '참석하면 참석자 명단과 대화를 볼 수 있어요.',
  createTitle: '소모임 만들기',
  fabLabel: '소모임 만들기',
  seatsTitle: '참석 현황',
  seatsCount: (joined: number, capacity: number) => `${joined} / ${capacity}명`,
  demographicsTitle: '지금 참석하는 사람들',
  demographicsNote: '개인 정보는 참석 후에만 볼 수 있어요.',
  participantsTitle: '참석자',
  chatTitle: '참석자 대화',
  chatPlaceholder: '참석자들에게 한마디 남겨보세요',
  hostedBy: (nickname: string) => `${nickname}님이 열었어요`,
  notFound: '존재하지 않는 소모임이에요.',
  share: '공유',
  shareCopied: '링크를 복사했어요.',
  createError: '소모임을 만들지 못했어요.',
  joinError: '참석 신청에 실패했어요.',
  leaveError: '취소에 실패했어요.',
} as const

export const PROFILE_COPY = {
  title: '내정보',
  followers: '팔로워',
  following: '팔로잉',
  followersCount: (n: number) => `팔로워 ${n}명`,
  followingCount: (n: number) => `팔로잉 ${n}명`,
  follow: '팔로우',
  followBack: '맞팔로우',
  unfollow: '팔로잉',
  message: '메시지 보내기',
  editProfile: '프로필 편집',
  shareProfile: '프로필 공유',
  settings: '설정',
  tabPosts: '수다글',
  tabReplies: '답글',
  tabBungaes: '소모임',
  emptyPosts: '아직 올린 수다글이 없어요.',
  emptyReplies: '아직 남긴 답글이 없어요.',
  emptyBungaes: '아직 열거나 참석한 소모임이 없어요.',
  repliedOn: '글에 남긴 답글',
  hostedTag: '리더',
  joinedTag: '참석',
  notFound: '존재하지 않거나 탈퇴한 사용자예요.',
  blockedNotice: '차단한 사용자예요. 차단을 해제하면 글을 볼 수 있어요.',
  noBio: '',
  completeTitle: '프로필 완성하기',
  completeBio: '소개 추가',
  completeBioDesc: '나를 한 줄로 소개하고 관심사를 알려주세요.',
  completePhoto: '사진 추가',
  completePhotoDesc: '프로필 사진을 올리면 알아보기 쉬워요.',
  completePost: '첫 수다글 쓰기',
  completePostDesc: '요즘 새벽 근무 이야기를 나눠보세요.',
  shareCopied: '프로필 링크를 복사했어요.',
  followListEmptyFollowers: '아직 팔로워가 없어요.',
  followListEmptyFollowing: '아직 팔로우하는 사람이 없어요.',
  searchPlaceholder: '닉네임 검색',
} as const

export const EDIT_PROFILE_COPY = {
  title: '프로필 편집',
  save: '완료',
  photoChange: '사진 변경',
  photoReset: '기본 이미지로',
  nickname: '닉네임',
  nicknameHint: (days: number) => `닉네임은 ${days}일에 한 번 바꿀 수 있어요.`,
  nicknameLocked: (date: string) => `${date} 이후에 닉네임을 바꿀 수 있어요.`,
  bio: '한줄소개',
  bioPlaceholder: '나를 한 줄로 소개해 주세요',
  workType: '근무 유형',
  offTime: '퇴근 시간대',
  region: '지역',
  showWorkBadge: '프로필에 근무 유형 표시',
  saved: '프로필을 저장했어요.',
  saveError: '저장하지 못했어요. 잠시 후 다시 시도해 주세요.',
  nicknameTaken: '이미 사용 중인 닉네임이에요.',
} as const

export const SETTINGS_COPY = {
  title: '설정',
  sectionAccount: '계정',
  sectionInfo: '정보',
  editProfile: '프로필 편집',
  changePassword: '비밀번호 변경',
  admin: '신고 관리(운영자)',
  blockedUsers: '차단한 사용자',
  blockedEmpty: '차단한 사용자가 없어요.',
  terms: '서비스 이용약관',
  privacy: '개인정보 처리방침',
  logout: '로그아웃',
  logoutConfirm: '로그아웃할까요?',
  withdraw: '회원탈퇴',
  withdrawTitle: '정말 탈퇴할까요?',
  withdrawBody: [
    '프로필, 올린 수다글·답글, 연 소모임, 주고받은 메시지, 올린 사진·파일이 모두 삭제돼요.',
    '삭제된 정보는 되돌릴 수 없어요.',
    '같은 이메일로 다시 가입할 수 있지만 이전 기록은 복구되지 않아요.',
  ],
  withdrawCheck: '안내를 모두 확인했어요',
  withdrawSubmit: '탈퇴하기',
  withdrawing: '탈퇴 처리 중이에요…',
  withdrawError: '탈퇴하지 못했어요. 잠시 후 다시 시도해 주세요.',
  withdrawDone: '탈퇴가 완료됐어요. 그동안 고마웠어요.',
  myInfo: '내 기본 정보',
  myInfoNote: '성별·출생연도는 나에게만 보여요.',
  gender: '성별',
  ageBand: '연령대',
  region: '지역',
} as const

export const NOTIFICATION_COPY = {
  tabMessages: '메시지',
  tabNotifications: '알림',
  empty: '아직 받은 알림이 없어요.',
  emptyHint: '내 글에 댓글이 달리거나, 메시지가 오거나, 내 소모임에 누가 참가하거나 댓글을 남기면 여기에 알려드려요.',
  markAllRead: '모두 읽음',
  settingsTitle: '알림 설정',
  settingsButton: '알림 설정',
  settingsDesc: '끈 알림은 앱 안 알림과 토스 푸시 모두 오지 않아요.',
  tossNote: '토스 앱 → 전체 → 설정 → 알림 → 서비스별 알림에서도 한 번에 끌 수 있어요.',
  saveError: '알림 설정을 저장하지 못했어요.',
  pushTitle: '토스 푸시 알림',
  pushDesc: '동의하면 토스 앱 푸시로도 알려드려요. 동의 화면이 몇 번 나올 수 있어요.',
  pushButton: '푸시 알림 받기',
  pushDone: '푸시 알림을 켰어요.',
  pushRejected: '동의하지 않은 알림은 푸시가 오지 않아요. 앱 안 알림은 계속 받아요.',
  pushFailed: '푸시 동의를 받지 못했어요. 잠시 후 다시 시도해 주세요.',
  types: {
    comment: { label: '댓글', desc: '내 수다글에 누가 댓글을 달았을 때' },
    comment_reply: { label: '답글', desc: '내가 단 댓글에 누가 답글을 남겼을 때' },
    bungae_comment: { label: '소모임 댓글', desc: '내 소모임에 댓글이 달리거나, 소모임에서 내 댓글에 답글이 달렸을 때' },
    dm: { label: '메시지', desc: '누가 나에게 메시지를 보냈을 때' },
    bungae_join: { label: '소모임 참가', desc: '내가 연 소모임에 누가 참가했을 때' },
  },
} as const

export const DM_COPY = {
  title: '메시지',
  empty: '아직 주고받은 메시지가 없어요.',
  emptyHint: '다른 사람 프로필에서 "메시지 보내기"를 누르면 대화를 시작할 수 있어요.',
  placeholder: '메시지 보내기…',
  send: '보내기',
  attach: '사진·파일 첨부',
  me: '나',
  attachmentPreview: '사진이나 파일을 보냈어요',
  startError: '대화를 시작하지 못했어요.',
  sendError: '메시지를 보내지 못했어요.',
  blocked: '차단한 사용자와는 메시지를 주고받을 수 없어요.',
  blockedByOther: '상대방이 차단했어요',
  safety: '처음 대화하는 사람에게 개인정보나 금전을 보내지 마세요. 불편한 메시지는 신고해 주세요.',
  read: '읽음',
  notFound: '대화를 찾을 수 없어요.',
} as const


export const FAB_COPY = {
  post: '새 글 쓰기',
} as const

export const AUTH_EXTRA_COPY = {
  subtitle: '새벽에 일하는 사람들의 SNS',
  emailPlaceholder: '이메일 주소',
  passwordPlaceholder: '비밀번호 (6자 이상)',
} as const

// 운영자 신고 관리(/admin). profiles.role = 'admin' 계정에만 보여요.
export const ADMIN_COPY = {
  title: '신고 관리',
  notice: '운영자만 볼 수 있는 화면이에요. Supabase 대시보드의 reports_overview 뷰에서도 같은 내용을 볼 수 있어요.',
  statusLabels: {
    pending: '대기',
    reviewing: '확인 중',
    resolved: '조치 완료',
    dismissed: '기각',
    all: '전체',
  },
  targetLabels: {
    post: '수다글',
    comment: '답글',
    bungae: '소모임',
    bungae_comment: '소모임 대화',
    user: '사용자',
  },
  reporter: '신고한 사람',
  detail: '직접 입력 내용',
  sameTarget: (n: number) => `같은 대상 신고 ${n}건`,
  open: '보러 가기',
  hide: '숨기기',
  unhide: '다시 보이기',
  hidden: '숨김 처리됨',
  deleted: '삭제되었거나 찾을 수 없어요',
  markReviewing: '확인 중',
  markResolved: '조치 완료',
  markDismissed: '기각',
  empty: '해당하는 신고가 없어요.',
  updateError: '처리하지 못했어요. 잠시 후 다시 시도해 주세요.',
} as const
